twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form_layout.html.twig'

twig_extra:
    markdown:
        enabled: true

when@test:
    twig:
        strict_variables: true
